---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  generateName: powervs-actuator-testing-machine-
  labels:
    machine.openshift.io/cluster-api-cluster: powervs-actuator-k8s
spec:
  providerSpec:
    value:
      apiVersion: powervsproviderconfig.openshift.io/v1alpha1
      kind: PowerVSMachineProviderConfig
      serviceInstanceID: e449d86e-c3a0-4c07-959e-8557fdf55482
      imageID: 45473216-7e3a-4711-8c14-28ada40a8de1
      userDataSecret:
        name: powervs-actuator-user-data-secret
      credentialsSecret:
        name: powervs-credentials-secret
      machineType: s922
      processorType: shared
      cores: 0.25
      memory: 4
      subnets:
        - daf2b616-542b-47ed-8cec-ceaec1e90f4d
      keyName: mkumatag-pub-key
